services:
  mongodb:
    image: mongo:7.0-jammy
    container_name: hotel-booking-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - hotel-booking-network

  backend:
    image: hotel-back:latest
    container_name: hotel-booking-backend
    restart: unless-stopped
    env_file:
      - ./server/.env   # هنا backend هيقرأ الـ .env بتاع السيرفر
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - hotel-booking-network

  frontend:
    image: hotel-front:latest
    container_name: hotel-booking-frontend
    restart: unless-stopped
    env_file:
      - ./client/.env   # لو محتاج الـ frontend يقرأ الـ .env بتاعه
    ports:
      - "5000:80"
    depends_on:
      - backend
    networks:
      - hotel-booking-network

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: hotel-booking-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - hotel-booking-network

  grafana:
    image: grafana/grafana:10.2.3
    container_name: hotel-booking-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    networks:
      - hotel-booking-network

networks:
  hotel-booking-network:
    driver: bridge

volumes:
  mongodb_data:
