apiVersion: v1
kind: ResourceQuota
metadata:
  name: hotel-app-quota
  namespace: hotel-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
    services: "10"
    configmaps: "20"
    persistentvolumeclaims: "5"
    secrets: "20"
